/***********************************************************************/
/*                                                                     */
/*  FILE        :PRB_RX62N.c                                           */
/*  DATE        :Fri, Apr 19, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  
#include <machine.h>
#include "iodefine.h"
#include "typedefine.h"


#define  LED0_PDR    PORTA.DDR.BIT.B2
#define  LED0        PORTA.DR.BIT.B2
#define  LED0_ON     PORTA.DR.BIT.B2 = 0
#define  LED0_OFF    PORTA.DR.BIT.B2 = 1
#define  LED1_PDR    PORTA.DDR.BIT.B1
#define  LED1        PORTA.DR.BIT.B1
#define  LED1_ON     PORTA.DR.BIT.B1 = 0
#define  LED1_OFF    PORTA.DR.BIT.B1 = 1
#define  LED2_PDR    PORTA.DDR.BIT.B0
#define  LED2        PORTA.DR.BIT.B0
#define  LED2_ON     PORTA.DR.BIT.B0 = 0
#define  LED2_OFF    PORTA.DR.BIT.B0 = 1
#define  SW1_PDR     PORT4.DDR.BIT.B6
#define  SW1         PORT4.DR.BIT.B6
#define	 SW1_ICR     PORT4.ICR.BIT.B6
//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

//**************************************************************************************
#pragma interrupt (ISR_TMR0(vect=176))
void ISR_TMR0(void);

#pragma interrupt (intMTU1ovf(vect=121))
void intMTU1ovf(void);

#pragma interrupt (SW1_IRQ14(vect=78))
void SW1_IRQ14(void);
		

//**************************************************************************************

void main(void)
{
	
	int cnt=0;
	
	// ICLK = EXTAL*8 = 12M*8 = 96 MHz. 
	SYSTEM.SCKCR.BIT.ICK  =  0;
	// PCLK = EXTAL*4 = 12M*4 = 48 MHz.
	SYSTEM.SCKCR.BIT.PCK  =  1;
	// BCLK = EXTAL*2 = 12M*2 = 24 MHz. 
	SYSTEM.SCKCR.BIT.BCK  =  2;
	// Enable BCLK output (high level). 
	SYSTEM.SCKCR.BIT.PSTOP1  =  0;	
	

	
	//SYSTEM.SCKCR.LONG = 0x00020100;
	
  
	
	//Configura puertos.
	
	LED0_PDR  = 1;  
    LED0      = 0;
	LED1_PDR  = 1;  
    LED1      = 0;
	LED2_PDR  = 1;  
    LED2      = 0;
	SW1_PDR   = 0;
	
    //Configura TMR0 
	
	// 256 *1/PCLK =256 * 20.8 ns = 5333 ns
	MSTP(TMR0) = 0; //Activate TMR0 unit
	IPR(TMR0,OVI0) = 7;        //prioridad 2
	TMR0.TCCR.BIT.CSS = 1;
	TMR0.TCCR.BIT.CKS = 6;     //48/8192Mhz
	TMR0.TCR.BIT.CCLR = 1;     //
    ICU.IR[176].BIT.IR = 0;  //flag a 0
  	IEN(TMR0,OVI0) = 1;	       //enable INT 
    TMR0.TCR.BIT.OVIE = 1; 
	
	
	     MSTP(MTU1) = 0;                  //habilita
		 MTU1.TCR.BIT.TPSC  = 2 ;          //48Mhz  PCLK
	     MTU1.TCR.BIT.CKEG  = 0 ;          //rising edge
		 MTU1.TCR.BIT.CCLR  = 1 ;          //TGRA
		 MTU1.TGRA          = 3225;
		 
		 MTU1.TIER.BIT.TGIEA = 1;         // INT ovf
		 IEN(MTU1,TGIA1)     = 1;
	     IPR(MTU1,TGIA1)     = 2;         // prioridad baja
		 IR(MTU1,TGIA1)      = 1;
	              // Start TCNT
	     MTUA.TSTR.BIT.CST1 = 1;           //start channel 1
	
    //sw1,irq14
	SW1_ICR = 1;
	
	// Configure falling-edge interrupts on corresponding IRQ's
	ICU.IRQCR[14].BIT.IRQMD = 1;

	
	// Clear IR flags for the IRQ's
	IR(ICU, IRQ14) = 0;

	
	// Set interrupt priority levels
	IPR(ICU, IRQ14) = 1;
	
	
	// Enable interrupts on the corresponding pins
	IEN(ICU, IRQ14) = 1;

	
	
	
	
	while(1){
		
	
		
		
	
		
	
	    delay_ms(100);
		LED2 ^= 1;		
		
	  }// fin while		

}//fin main

//**********************************************************************
void intMTU1ovf(void)
{
	static unsigned char cnt=0;
 
    if(++cnt > 200)  //aprox 100ms
    {  
    LED1 ^= 1 ;   //2 seg
	cnt=0;
    }		
	

}

//****************************************************************
void SW1_IRQ14(void)
{
	
	  LED2 ^= 1;	
	
}
//*****************************************************************
void ISR_TMR0(void){
	
	static unsigned char cnt=0;
	
	if(++cnt > 6)
	{

	 LED0 ^= 1 ; //aprox 1 seg
	 cnt=0;
	} 
	
}		
//********************************************************************************

#ifdef __cplusplus
void abort(void)
{

}
#endif
